### ISSUE TITLE
findRelationshipsByProperty returning unmatching instances

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria-connector-ibm-information-server#214]
During CTS testing using the relationship search test case, the above method is seen to return instances that are not a match for the search parameters.

The concrete example is:

Type: DataClassAssignment
There are reported to be 53 instances of this type in the repository.
Only 7 instances have the property "partialMatch" set - in all 7 it is set to "true"
These 7 instances also have values for "confidence", "valueFrequency" and "status"

Performing findRelationhsipsByProperty with a MatchProperties parameter containing partialMatch : true and  matchCriteria set to ALL, the method returned 26 results. Only 7 of the returned instances contained a value for partialMatch.

I am happy to reproduce and provide screen dumps if it helps.

**Comment by cmgrote** [comment]
I believe I've fixed some of the mapping in this example quite recently, as there were previously some errors in the way that `partialMatch` was being handled, specifically.  Of course, it's possible that I also introduced some other bug(s) in the process...

Not to worry, I'll re-test and investigate.

**Comment by grahamwallis** [comment]
Could well be that you have already fixed - I last pulled and built on the 15th

**Comment by grahamwallis** [comment]
Update - still seeing this with latest CTS test against current master
